[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."editoriaux"]
  included_files = [".netlify/private-editorials.json"]

[functions."editorial-content"]
  included_files = [".netlify/private-editorials.json"]
